### ISSUE TITLE
pksc write - secret incorrect?

### ISSUE THREAD

**Issue by neilfx1** [arthurdejong/python-pskc#5]
Hi, 

Just a question as I may be doing something wrong here.  I'm generating a pskc file which writes out correctly, however the OTP timebase is always wrong.  After tracing back where the issue is it looks like when I call 
pskc.write('filename.pskc') it is replacing my generated secret with another one - I'm not entirely sure why! 

I've zipped up the test files - the issue is essentially the secret is coming out as **THlrTHVYdGErOXhHeWF3c2lVclkxVmpRTklBPQ==** 
and it should be:
**LykLuXta+9xGyawsiUrY1VjQNIA=**

[issue.zip](https://github.com/arthurdejong/python-pskc/files/7927554/issue.zip)

Are you able to suggest what the issue could be here?  

Thanks,

Neil

**Comment by neilfx1** [comment]
Little update - I've traced it back to serialiser.py and this function:

```
def my_b64encode(value):
    """Wrap around b64encode to handle types correctly."""
    if not isinstance(value, type(b'')):
        value = value.encode()  # pragma: no cover (Python 3 specific)
    return base64.b64encode(value).decode()
```

What I don't get is what I need to feed into value (via secret=) to stop it changing the secret.  Any ideas appreciated!

**Comment by arthurdejong** [comment]
By the way, the recommended way to set up encryption of the output to use the `setup_preshared_key()` function because it also allows configuring which fields of the key data will actually be encrypted.

But the main problem in your example code is that you should pass in the data for key as binary, not the already base64-encoded data. That means you need to change

    key = pskc.add_key(secret=b64sec2)

to

    key = pskc.add_key(secret=bytes(ba))

I'll look into also supporting `bytearray` values.

**Comment by neilfx1** [comment]
Thanks, that has resolved the problem! For reference my original non testing code has `setup_preshared_key()` in there and that one is now working as expected.
